"""IPC: admin socket, bearer leases, consent rendezvous, tunnel pins."""

from comms.transports.telegram.ipc.admin import (
    ADMIN_COMMANDS,
    AdminRouter,
    PeerCredentials,
    getpeereid,
    peer_credentials,
    serve_admin,
    verify_peer,
)
from comms.transports.telegram.ipc.framing import (
    IDLE_TIMEOUT_S,
    MAX_FRAME_BYTES,
    FrameError,
    decode_json_frame,
    encode_json_frame,
    read_frame,
    write_frame,
)
from comms.transports.telegram.ipc.leases import (
    LEASE_AUDIENCE,
    LEASE_MAX_CHARS,
    LEASE_MAX_LIFETIME_S,
    LEASE_MAX_SKEW_S,
    LeaseClaims,
    LeaseError,
    mint_lease,
    verify_lease,
)
from comms.transports.telegram.ipc.rendezvous import (
    HANDSHAKE_DEADLINE_S,
    RV_VERSION,
    RendezvousError,
    RendezvousSession,
    build_challenge,
    serve_rendezvous,
    transcript_digest,
)
from comms.transports.telegram.ipc.tunnel import (
    PIN_LIFETIME_DAYS,
    TunnelPin,
    TunnelPinError,
    add_pin,
    current_pin,
    pin_history,
    rotate_binding,
    spki_digest,
    verify_pin,
)

__all__ = [
    "ADMIN_COMMANDS",
    "HANDSHAKE_DEADLINE_S",
    "IDLE_TIMEOUT_S",
    "LEASE_AUDIENCE",
    "LEASE_MAX_CHARS",
    "LEASE_MAX_LIFETIME_S",
    "LEASE_MAX_SKEW_S",
    "MAX_FRAME_BYTES",
    "PIN_LIFETIME_DAYS",
    "RV_VERSION",
    "AdminRouter",
    "FrameError",
    "LeaseClaims",
    "LeaseError",
    "PeerCredentials",
    "RendezvousError",
    "RendezvousSession",
    "TunnelPin",
    "TunnelPinError",
    "add_pin",
    "build_challenge",
    "current_pin",
    "decode_json_frame",
    "encode_json_frame",
    "getpeereid",
    "mint_lease",
    "peer_credentials",
    "pin_history",
    "read_frame",
    "rotate_binding",
    "serve_admin",
    "serve_rendezvous",
    "spki_digest",
    "transcript_digest",
    "verify_lease",
    "verify_peer",
    "verify_pin",
    "write_frame",
]
